import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';

const poppins = Poppins({
    weight: ['400', '900'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Portal | Web Briks LLC',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="icon"
                    href="https://iili.io/dj5tSSf.png"
                    type="image/png"
                />
            </head>
            <body className={`${poppins.className} antialiased`}>
                {children}
            </body>
        </html>
    );
}
